[nfs]
172.31.2.76 ansible_ssh_user='ec2-user'

[webservers]
172.31.5.159 ansible_ssh_user='ec2-user'
172.31.5.225 ansible_ssh_user='ec2-user'

[db]
172.31.13.86 ansible_ssh_user='ec2-user' 

[lb]
172.31.37.221 ansible_ssh_user='ubuntu'