# roles/webserver/tasks/main.yml

- name: install apache
  become: true
  ansible.builtin.yum:
    name: "httpd"
    state: present

- name: install git
  become: true
  ansible.builtin.yum:
    name: "git"
    state: present

- name: clone a repo
  become: true
  ansible.builtin.git:
    repo: "{{ webserver_repo_url }}"
    dest: "{{ webserver_dest }}"
    force: yes

- name: copy html content to one level up
  become: true
  command: cp -r "{{ webserver_src }}" /var/www/

- name: Start service httpd, if not started
  become: true
  ansible.builtin.service:
    name: "{{ webserver_service_name }}"
    state: started

- name: recursively remove /var/www/html/html/ directory
  become: true
  ansible.builtin.file:
    path: "{{ webserver_dest }}/html"
    state: absent
