---
- name: update web and nfs servers
  hosts: webservers, nfs
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest
      ignore_errors: yes

    - name: Ensure python3-apt is installed on Debian/Ubuntu
      become: yes
      apt:
        name: python3-apt
        state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Ensure yum is installed on Red Hat
      become: yes
      package:
        name: yum
        state: present
      when: ansible_distribution == 'RedHat'

    - name: Remove Node.js and npm on Debian/Ubuntu
      become: yes
      apt:
        name: 
          - nodejs
          - npm
        state: absent
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Remove Node.js and npm on Red Hat
      become: yes
      yum:
        name: 
          - nodejs
          - npm
        state: absent
      when: ansible_distribution == 'RedHat'

- name: update LB and DB server
  hosts: lb, db
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Update apt repo
      become: yes
      apt: 
        update_cache: yes

    - name: ensure wireshark is at the latest version
      become: yes
      apt:
        name: wireshark
        state: latest
      ignore_errors: yes

    - name: Update apt repo and cache
      become: yes
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Remove Node.js and npm
      become: yes
      apt:
        name: 
          - nodejs
          - npm
        state: absent


