---
- name: update web and nfs servers
  hosts: webservers, nfs
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      # Use 'yum' for Red Hat-based systems
      yum:
        name: wireshark
        state: latest
      when: ansible_os_family == "RedHat"

    - name: ensure wireshark is at the latest version
      # Use 'apt' for Debian-based systems
      apt:
        name: wireshark
        state: latest
      when: ansible_os_family == "Debian"

- name: update LB and DB server
  hosts: lb, db
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Update apt repo
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest
